# Pipeline configuration file for training a U-Net model on random reconstruction data.
# The model is defined in Framework-SSL/configs/models/single_channel_unet.yaml.
# The trainer is defined in Framework-SSL/configs/trainer/default.yaml.
# The data module is defined in Framework-SSL/configs/data/random_reconstruction_data.yaml.

# --------------------- INIT ARGS ---------------------
# Model configuration file
model: "/workspaces/seismic/Framework-SSL/configs/models/single_channel_unet.yaml"
# Trainer configuration file
trainer: "/workspaces/seisic/Framework-SSL/configs/trainer/default.yaml"
log_dir: null
# --------------------- RUN ARGS (Pipeline's entry-point) ---------------------
run:
  # Set the task to train
  task: fit
  # Data configuration file
  data: "/workspaces/seismic/Framework-SSL/configs/data/random_reconstruction_data.yaml"