# Configuration file for the Trainer class.

# Class and __init__ arguments.
class_path: lightning.Trainer
init_args:
  # Accelerator to use (CPU, GPU, TPU, ..).
  accelerator: gpu
  # Number of accelerator devices to use.
  devices: 1
  # Strategy to use for distributed training.
  strategy: auto
  # Maximum number of epochs to train.
  max_epochs: 100
  # Logger and callback configuration (load from file)
  logger: "/workspaces/seismic/minerva-seismic/configs/loggers/default.yaml"
  callbacks: "/workspaces/seismic/minerva-seismic/configs/callbacks/default_train.yaml"